
//OPERADORES ARITMÉTICOS 
console.log(x + y);
console.log(x * y);
console.log(x - y);
console.log(x / y);

//OPERADORES DE COMPARAÇÃO
console.log("5" == 5); // IGUAL
console.log("5" === 5); //EXTRITAMENTE IGUAL
console.log(x != y); //DIFERENTE 
console.log(x !== y);  //DIFERENTE OU IGUAL

//OPERADORES LÓGICOS

//AND      &&   
//OR       ||

console.log(10 > 5 && 20 < 30) 
console.log(10 > 11 || 20 < 30)

// && só vai considerar verdadeiro se as duas solicitações forem verdadeiras
// || se ao menos uma for verdadeira ele passa  